"""empty message

Revision ID: 23d0832efdaa
Revises: 
Create Date: 2017-10-29 19:00:41.746000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d0832efdaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmpareq01', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmpareq01', 'status')
    # ### end Alembic commands ###
