"""empty message

Revision ID: 696e45ca0445
Revises: 23d0832efdaa
Create Date: 2017-11-04 13:05:46.108000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '696e45ca0445'
down_revision = '23d0832efdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asppreq01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_socio', sa.Integer(), nullable=True),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('total_amount', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tmpareq01')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmpareq01',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'tmpareq01_pkey')
    )
    op.drop_table('asppreq01')
    # ### end Alembic commands ###
